---
version: '3.5'

services:
    sunportal-nginx:
        container_name: 'sunportal_nginx'
        image: nginx:latest
        restart: 'always'
        ports:
            - 80:80
        volumes:
            - './resources/sunportal.conf:/etc/nginx/conf.d/default.conf'
        networks:
          - sunportal
    
    sunportal:
        image: "larsvanrhijn/sunportal:latest"
        restart: 'always'
        container_name: sunportal
        depends_on:
          - 'sunportal-nginx'
        expose:
            - '8000'
        volumes:
            - './log/:/sunportal/log/'
            - '/home/pi/smadata/SBFspot.db:/sunportal/db/database.db'
        
        networks:
        - sunportal

networks:
  sunportal:
    driver: bridge
