---

name: Build Production Docker Image
on:
  pull_request:
    branches: [ master ]

jobs:
    build-docker:
        name: "Build Production Docker Image"
        runs-on: "ubuntu-latest"
        env:
            DOCKER_LATEST: docker.pkg.github.com/kioui/sunportal/sunportal:latest
            DOCKER_TAG_PRODUCTION: docker.pkg.github.com/kioui/sunportal/sunportal:${{ github.sha }}
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v2"

            - name: "Build Docker image"
              run: |
                  docker buildx create --use --name  sunportal
                  docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --tag "${DOCKER_LATEST}" .

            - name: "Login to GitHub"
              run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u KiOui --password-stdin
            
            - name: "Tag and publish"
              run: |
                  docker tag "${DOCKER_LATEST}" "${DOCKER_TAG_PRODUCTION}"
                  docker push "${DOCKER_TAG_PRODUCTION}"
                  docker push "${DOCKER_LATEST}"
